# Generated by Django 4.2.4 on 2023-09-02 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='idActividad',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='idActividad',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='idPregunta',
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
    ]
